In [1]:
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer

from sentence_transformers import SentenceTransformer
#导入停用词
# stop_word = [line.strip() for line in open('baidu_stopwords','r', encoding='utf-8')]
stop_word = []
PATH = "../1爬取关键词微博/temp.txt"
data_set = []  #用于存储文档
for line in open(PATH, encoding='utf-8'):
    data_set.append(line.strip())

#加载可以对句子进行embedding的模型，这里选的是SentenceTransformer中的多语言模型，因为这个转向量特别快，
#当然也可以用一些古汉语相关的模型，'SIKU-BERT/sikubert'
sentence_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
#将所有的句子都转化为embedding
embeddings = sentence_model.encode(data_set, show_progress_bar=True)
print(embeddings.shape) #输出句子的embedding的维度
print(embeddings[0]) #输出第一句话的embedding
print('句子的个数：',len(data_set)) #输出句子的个数

Batches:   0%|          | 0/4550 [00:00<?, ?it/s]

(145576, 384)
[ 1.33381829e-01 -1.02593834e-02 -3.00869256e-01 -1.53919727e-01
  4.19450691e-03  7.75943249e-02  2.67699026e-02  4.23249491e-02
  2.26036176e-01  6.20238706e-02  4.34905365e-02  4.76566032e-02
 -1.09936990e-01  1.64580077e-01 -1.40863925e-01  3.80894244e-02
 -1.07321464e-01 -1.99541688e-01 -4.65789586e-01  1.58822373e-01
 -1.94782287e-01 -1.73101097e-01  2.12811697e-02 -5.90208359e-02
 -1.24288745e-01 -3.81187513e-03 -8.36784542e-02  5.88395745e-02
 -3.14124942e-01 -7.88011064e-04 -1.68225691e-01 -1.85170978e-01
 -1.18865585e-02  2.99947709e-01 -3.34261835e-01  6.49362206e-02
 -7.16931447e-02  5.65148853e-02  2.67116576e-02 -7.27385953e-02
  1.67813629e-01 -4.14574146e-03 -1.03533268e-01  3.80443037e-02
 -8.89464021e-02  1.29088849e-01  1.36969596e-01  9.59351659e-02
 -1.59006745e-01 -3.82548243e-01 -8.86755735e-02  2.36576274e-02
  1.04460984e-01  2.83166349e-01 -1.00357592e-01  5.60864881e-02
 -1.27607137e-01 -2.93512732e-01 -8.97691865e-03  2.81805806e-02
  5.02930209e-02 -1.44734919e-01 -1.06287181e-01  1.90794200e-01
 -4.30053510e-02 -5.73063679e-02 -2.88455725e-01  9.33868624e-03
 -9.90265608e-02  8.83411542e-02 -6.67684508e-05  1.73761979e-01
 -3.13642800e-01  3.62489939e-01  2.50961363e-01 -7.02934414e-02
 -5.78795485e-02 -2.58804947e-01  1.69254735e-01  1.33391455e-01
  1.30477279e-01  2.19706044e-01  2.21775576e-01  1.66370183e-01
 -1.12575591e-01 -2.67563760e-02  1.58555582e-01  1.02591589e-01
  1.11065786e-02 -2.38521770e-01  1.55046120e-01  1.43285081e-01
  1.09456316e-01 -3.85846078e-01  1.50124863e-01  1.79170921e-01
  8.16919655e-02  2.20925167e-01 -2.03254983e-01 -1.10654473e-01
 -3.13175231e-01 -1.94630355e-01  5.90374693e-03  4.13955189e-02
  2.38108575e-01 -1.43011123e-01  2.25238189e-01 -5.64652123e-02
  2.22619087e-01  7.52680004e-02 -1.04021624e-01 -1.97197884e-01
  1.04116676e-02 -1.94002353e-02  3.00710559e-01  4.40958589e-02
 -1.69108987e-01  1.73576027e-01  2.25536630e-01 -2.31064603e-01
  4.09047641e-02 -2.08890229e-01  2.78068632e-01  1.47709381e-02
  3.42900664e-01  1.08676903e-01  1.85907558e-01  1.08293891e-01
 -1.43351316e-01 -8.55057836e-02  2.62109071e-01  2.94697694e-02
 -2.13324577e-02  1.41703948e-01 -3.03295851e-02 -1.54024810e-01
  2.87117392e-01  1.96131885e-01 -1.34020641e-01  2.57977694e-01
  4.57797498e-01  2.73942053e-01 -1.10291362e-01  4.45261031e-01
  1.07797407e-01  2.03791454e-01 -5.58819249e-02 -3.42085236e-03
  1.87047496e-01 -7.89009407e-03  2.30868831e-01  2.16098323e-01
 -2.44410530e-01 -4.24444824e-01  7.28541985e-02 -1.30915448e-01
  6.84081763e-02 -2.49667559e-02 -1.42774612e-01 -5.79929259e-03
  1.63367674e-01 -1.00110412e-01  1.16877213e-01  1.45266175e-01
 -8.73090252e-02 -1.23141125e-01 -1.26185073e-02 -5.43617606e-02
  2.31638104e-01 -2.41737306e-01  1.00975759e-01 -1.42611712e-01
 -1.11085728e-01  1.62117347e-01 -1.32331580e-01 -3.11746478e-01
 -1.72817111e-01  4.88093674e-01  1.07886948e-01  1.97108194e-01
 -1.38607457e-01 -2.20595852e-01 -2.28026375e-01  2.39622369e-01
 -2.14064270e-01  6.62134290e-02  2.23160107e-02  6.96030259e-02
 -2.43322819e-01 -1.66744560e-01  6.88737109e-02  4.73398268e-02
  1.57134727e-01  5.59065118e-02 -4.33995202e-02 -3.26268077e-01
  1.28782541e-01 -1.87368110e-01 -1.01796404e-01 -1.11296717e-02
 -3.30294847e-01  1.13147311e-01 -4.20702323e-02 -1.16586991e-01
 -1.51824757e-01  3.83643918e-02  2.67740637e-01  1.09084696e-02
  2.47370396e-02  1.67190239e-01 -8.70261118e-02  7.73020834e-02
 -1.93775028e-01 -1.53317764e-01  7.08790570e-02  1.34619430e-01
 -2.18868971e-01  2.49721199e-01  1.48005083e-01 -1.52254780e-03
 -1.15177138e-02  1.85795069e-01  3.83337326e-02 -2.02960119e-01
 -1.38999313e-01 -2.08599716e-01  2.07967147e-01 -9.09753442e-02
  7.83428401e-02  2.68653005e-01  1.29191577e-01 -9.37355682e-02
  9.63532403e-02  1.48341775e-01  9.73227695e-02 -1.98651135e-01
  3.15260351e-01 -5.84999733e-02  6.80583641e-02  4.58207652e-02
 -2.48900622e-01 -1.97847709e-01 -7.72509724e-02  8.72983690e-03
 -1.26057163e-01  2.61255503e-01  5.76626882e-02 -6.27121851e-02
 -6.55923709e-02  2.78827161e-01  5.34614511e-02 -9.87787768e-02
  1.19695030e-01 -2.04876453e-01 -2.67115265e-01  3.20339322e-01
 -4.41047162e-01 -4.61810753e-02  6.42248467e-02  1.15347773e-01
 -1.79038301e-01  1.11557670e-01 -7.59517476e-02  7.87047818e-02
 -1.72867309e-02  1.09941423e-01 -3.21243942e-01  6.27680123e-02
  2.00253889e-01  1.90587163e-01  1.20678090e-01 -1.69994906e-01
 -1.12993099e-01 -7.55519792e-02 -5.46556860e-02  8.91037881e-02
  1.74351856e-01 -1.62823781e-01  2.17354000e-01  9.26005468e-02
  1.14010915e-01 -1.11956589e-01  1.02230817e-01  3.28753814e-02
  3.10545266e-01  6.76647155e-03  1.43754959e-01  7.06574917e-02
  1.04986571e-01 -4.19066660e-02 -4.90999147e-02  3.74364816e-02
  5.38379215e-02 -2.42278464e-02  7.45423064e-02 -2.90538311e-01
 -8.31286609e-02 -3.11163694e-01  1.52713656e-01 -1.16848992e-02
 -3.40948105e-01 -1.16372988e-01 -3.09170753e-01 -1.54962376e-01
  6.00309558e-02 -2.65264541e-01  1.15203783e-01  2.23820448e-01
 -1.20489940e-01 -4.69821356e-02  3.67707670e-01 -1.16264343e-01
  1.82180494e-01  2.43225843e-01 -1.32852629e-01 -7.41160437e-02
 -3.75422597e-01 -1.73978806e-01  9.56886411e-02 -1.21467508e-01
  1.88442264e-02  4.61872518e-02 -2.43273549e-04 -1.36819750e-01
  1.49275616e-01  9.70899314e-02 -1.20728508e-01  2.05090761e-01
 -1.84095562e-01  3.92960489e-01 -3.34149338e-02  1.22762017e-01
  2.31149212e-01 -1.39056832e-01  4.35768701e-02  1.37700155e-01
 -3.69738907e-01 -1.25421852e-01 -4.58279066e-02  1.76489189e-01
  1.62618309e-01  3.08637284e-02 -8.75733197e-02  8.51305053e-02
  3.01591486e-01  1.75755411e-01 -1.04963347e-01  6.80274749e-03
  9.41627622e-02  1.25835657e-01  7.24862590e-02 -1.09494381e-01
 -1.22090034e-01  2.95482785e-01  6.71905056e-02 -2.56452680e-01
 -2.25182801e-01 -1.08222879e-01  1.90137744e-01 -3.09649855e-01
 -1.85369506e-01  7.72952586e-02  2.99919043e-02  4.14993912e-02
 -2.34247625e-01 -5.65299578e-02 -7.98978955e-02 -8.33009928e-02
 -1.91493705e-01 -1.40466720e-01 -4.32478311e-03 -3.51050273e-02
  4.14959863e-02  2.33878389e-01 -1.38301983e-01 -1.43999055e-01
  2.43982412e-02  9.79491249e-02 -4.60815467e-02 -1.44786522e-01
 -4.18283865e-02  1.94524080e-01  4.69821729e-02 -1.40689582e-01]
句子的个数： 145576

In [27]:
# from bertopic import BERTopic
# import umap 
# import hdbscan
# # Create instances of GPU-accelerated UMAP and HDBSCAN
# umap_model = umap.UMAP(n_components=5, n_neighbors=15, min_dist=0.0)
# hdbscan_model = hdbscan.HDBSCAN(min_samples=10, gen_min_span_tree=True, prediction_data=True)
# vectorizer_model = CountVectorizer(stop_words=stop_word,analyzer='word', token_pattern=u"(?u)\\b\\w+\\b")
# 
# topic_model = BERTopic(
#     # embedding_model=embedding_model,    # Step 1 - Extract embeddings
#     umap_model=umap_model,              # Step 2 - Reduce dimensionality
#     hdbscan_model=hdbscan_model,        # Step 3 - Cluster reduced embeddings
#     vectorizer_model=vectorizer_model,  # Step 4 - Tokenize topics
#     # ctfidf_model=ctfidf_model,          # Step 5 - Extract topic words
#     nr_topics=10,
#     top_n_words=30,
#     language="multilingual"
# )
# topic = topic_model.fit(data_set, embeddings)

In [2]:
#然后初始化CountVectorizer，在bertopic中计算tf-idf需要用到的，这时候要加载停用词，  作者建议在聚类之后再使用停用词，因为句子embedding需要句子完整，如果一开始就去停用词，会导致embdding语义不完整
#所以在 CountVectorizer中才使用停用词，其实也就是不计算停用词对主题类的重要性
vectorizer_model = CountVectorizer(stop_words=stop_word,analyzer='word', token_pattern=u"(?u)\\b\\w+\\b")
#这里analyzer='word', token_pattern=u"(?u)\\b\\w+\\b" 的设置就是针对汉语的，因为汉语词既可以是单字词，又可以是多字词
topic_model = BERTopic(vectorizer_model=vectorizer_model, top_n_words=30,language="multilingual")
topic = topic_model.fit(data_set, embeddings)

<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>

In [3]:
topic.get_topic_info()

<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>
<pandas._libs.index.ObjectEngine object at 0x000002279EF242E0>

,Topic,Count,Name,Representation,Representative_Docs
0,-1,62178,-1_就_去_没_我,"[就, 去, 没, 我, 不, 一个, 看, 说, 了, 会, 想, 得, 还是, 还, 什...","[艾滋病 想 知道 大家 都 怎么 被 感染 的, 我 知道 他 有 艾滋 但 我 还是 想..."
1,0,1522,0_他_二时_何谓_金山,"[他, 二时, 何谓, 金山, 千古, 刚刚, 发颤, 查出, 失足, 被子, 告诫, 勇于...",[他 曾 在 大 二时 嫖娼 刚刚 查出 艾滋病毒 携带 23 岁 大 三 男生 蒙 被子 ...
2,1,1508,1_同性恋_骗婚_异性恋_男,"[同性恋, 骗婚, 异性恋, 男, 金牌, 免, 高贵, 不得好死, 特权, 恶心, 出柜,...","[我 不 歧视 同性恋 也 不 歧视 艾滋 歧视 的 是 得 艾滋 的 男 同性恋, 同性恋..."
3,2,1260,2_入校_儿童_7_携带,"[入校, 儿童, 7, 携带, 无法, 岁, 孩子, 家长, 艾滋病毒, 学校, 小孩, 小...","[7 岁 艾滋病毒 携带 儿童 无法 入校 这种 父母 真的 是, 7 岁 艾滋病毒 携带 ..."
4,3,1224,3_男人_嫖娼_女人_同,"[男人, 嫖娼, 女人, 同, 男, 男性, 女, 女权, 女性, 妓女, 脏, 嫖, 男女...",[男朋友 问 我 男朋友 出轨 和 嫖娼 哪个 最 不能 接受 我 说 嫖娼 吧 你 要是 ...
...,...,...,...,...,...
1885,1884,10,1884_怜_庆_首_藏于,"[怜, 庆, 首, 藏于, 场景, 歌, 追光, 垃圾岛, 茫茫, 嗓音, 起航, 逐, 单...",[朴实无华 的 摄影 作品 不离不弃 却 触碰 到了 心底 最 柔软 的 部分 相依相偎 有...
1886,1885,10,1885_幻_仙_科技_印钞机,"[幻, 仙, 科技, 印钞机, 僭, 美联储, 基站, 工业设计, 交费, 断言, 硬件, ...",[第五代 移动 通信 技术 到底 对 人体 有 什么 健康 隐患 言之凿凿 的 人 哪个 可...
1887,1886,10,1886_求异_传播者_异性恋_顺,"[求异, 传播者, 异性恋, 顺, 主观, 色彩, 天下无双, 泣鬼神, 惊天地, 判为, ...",[而且 想说 一句话 即使 性 少数 是 艾滋病 性病 的 主要 传播者 性 少数 也 不 ...
1888,1887,10,1887_1331_用心_生日快乐_王俊,"[1331, 用心, 生日快乐, 王俊, 好棒, 恶魔, 应援, 带动, 覆盖面, 凯, 二...",[王俊 凯 王俊 凯 0921 生日快乐 好棒 呀 王俊 凯 1331 名 通过 母婴 传播...
1889,1888,10,1888_直说_检查出来_并发症_捐,"[直说, 检查出来, 并发症, 捐, 翻译, 法, 谈恋爱, 查出来, 之类, 献血, 进化...",[我的天 得了 病 查 不 出来 还 能 正常 献血 谈恋爱 什么 的 翻译 一下 就是 艾...

In [5]:
first_new_topic_probs = topic_model.visualize_documents(data_set, embeddings=embeddings)
first_new_topic_probs.write_html('visualize_documents.html')

<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x0000022812B30580>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B30580>
<pandas._libs.index.Int64Engine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010F7C0>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.ObjectEngine object at 0x0000022812B33760>
<pandas._libs.index.Int64Engine object at 0x00000227A010EF80>

In [6]:

out = topic_model.visualize_hierarchy(top_n_topics=380)
out.write_html('visualize_hierarchy.html')

<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>
<pandas._libs.index.ObjectEngine object at 0x00000227A010EF80>

In [ ]:
first_new_topic_probs = topic_model.visualize_heatmap()
first_new_topic_probs.write_html('visualize_heatmap.html')

In [ ]:
first_new_topic_probs = topic_model.visualize_term_rank()
first_new_topic_probs.write_html('visualize_term_rank.html')

In [ ]:
first_new_topic_probs = topic_model.visualize_topics()
first_new_topic_probs.write_html('visualize_topics.html')

In [4]:

hierarchical_topics = topic_model.hierarchical_topics(data_set)

100%|██████████| 2310/2310 [00:59<00:00, 39.06it/s]

In [5]:
hierarchical_topics

,Parent_ID,Parent_Name,Topics,Child_Left_ID,Child_Left_Name,Child_Right_ID,Child_Right_Name,Distance
2309,4620,吴宣仪_网易_谢谢_狗_尤长靖,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",4405,吴宣仪_火箭_笑语_罗_小昂,4619,网易_谢谢_狗_尤长靖_邓伦,3.270074
2308,4619,网易_谢谢_狗_尤长靖_邓伦,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",4618,网易_谢谢_狗_邓伦_大熊猫,4616,心瘾_尤长靖_韬_黄子韬_演唱会,3.069573
2307,4618,网易_谢谢_狗_邓伦_大熊猫,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",4617,网易_谢谢_狗_邓伦_大熊猫,4520,龚俊_子俊俊_龚俊西_蒙俊_韩烨,3.062487
2306,4617,网易_谢谢_狗_邓伦_大熊猫,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",4615,网易_谢谢_狗_大熊猫_邓伦,2745,热巴_迪丽_力士_金纺迪丽_李长歌,2.809955
2305,4616,心瘾_尤长靖_韬_黄子韬_演唱会,"[91, 165, 166, 182, 189, 197, 245, 301, 318, 3...",4613,尤长靖_西柚_新歌_亚洲_榜,4610,心瘾_韬_黄子韬_冰激凌_演唱会,2.759829
...,...,...,...,...,...,...,...,...
4,2315,心瘾_韬_韬黄子_韬刷_韬才,"[590, 1384, 2139]",2311,心瘾_韬_韬黄子_韬刷_胡汉三,1384,心瘾_韬_韬才_胡汉三_下雨天,0.053366
3,2314,缺土_金旺_属猪_双子_牧民,"[646, 1872]",646,缺土_金旺_属猪_双子_牧民,1872,缺土_金旺_属猪_双子_响爷,0.050236
2,2313,脖_鸭哥_精武_精研_五香,"[1097, 1366]",1366,脖_鸭哥_精武_精研_五香,1097,脖_鸭哥_精武_精研_五香,0.030981
1,2312,阳阳_阳光_范_周翊然_霸道,"[261, 1700]",261,阳阳_阳光_范_周翊然_霸道,1700,阳阳_晚安_阳光_宝贝_时间,0.029309
0,2311,心瘾_韬_韬黄子_韬刷_胡汉三,"[590, 2139]",590,心瘾_韬_韬黄子_韬刷_胡汉三,2139,心瘾_韬_韬刷_胡汉三_韬黄子,0.013831

In [7]:
import  jiagu
sss = jiagu.sentiment('只字不提艾滋阳性好吧为了稳定')

In [11]:
sss[1]

0.6527195473956697